# app.py
# Generated by AgentKit Studio
# Automation: viva generator

from agentkit import Agent
from tools import clean_text, extract_keywords, list_files, read_file, write_file


agent = Agent(
    name='viva generator',
    model='llama3',
    goal='Build a smart AI Viva Generator that helps students prepare for academic Vivas by generating relevant questions, answers, and mock viva sessions from uploaded study materials using Natural Language Processing and Machine Learning techniques.',
    tools=[
        clean_text,
        extract_keywords,
        list_files,
        read_file,
        write_file
    ],
    max_steps=12,
    safe_mode=True,
    temperature=0.2,
)

agent.run("""
Read manual.txt from ./input.

Extract important topics from the file.

Generate 10 viva questions and answers based on the extracted topics.

Create markdown formatted content with headings, questions, and answers.

Write all generated content into ./output/viva_generator.md.
""")
